services:
  # Backend API Service
  - type: web
    name: otr-baseball-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://otr-baseball-frontend.onrender.com
    healthCheckPath: /api/health

  # Frontend Web Service
  - type: web
    name: otr-baseball-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://otr-baseball-backend.onrender.com/api
      - key: VITE_APP_NAME
        value: OTR Baseball Analytics
      - key: VITE_APP_VERSION
        value: 1.0.0

databases:
  # PostgreSQL Database
  - name: otr-baseball-db
    databaseName: otrbaseball
    user: otrbaseball_user
    plan: free 