services:
  # Backend API Service
  - type: web
    name: otr-baseball-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://otr-data.com
    healthCheckPath: /api/health

databases:
  # PostgreSQL Database
  - name: otr-baseball-db
    databaseName: otrbaseball
    user: otrbaseball_user
    plan: free 